services:
  frontend-wsg:
    build: frontend/
    container_name: frontend
    ports:
      - "3000:3000"

  redis-wsg:
    build: redis/
    container_name: redis
    networks: 
      - wsg

  controller-wsg:
    build: controller_service/
    container_name: controller
    depends_on:
      - redis-wsg
    ports:
      - "8080:8080"
    dns:
      - 1.1.1.1
    networks: 
      - wsg

  classifiers-wsg:
    build: classifiers/
    container_name: classifiers
    networks: 
      - wsg

networks:
  wsg:
    driver: bridge